### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by thiagotsalles** [thiagotsalles/BayesianGrowhModelling#1]
- [x] Change the way the data in the script is handled. It should be loaded into a data frame.

- [x] Code to build all plots with ggplot2.

- [x] Change what is being done with OpenBugs to Jags.
